### ISSUE TITLE
Plugin not working in external source

### ISSUE THREAD

**Issue by cerebrumgit** [markets/jekyll-timeago#10]
Hello, good morning

If you can help me

I have the following occurrence

As images we see that in the local environment runs the plugin "Jekyll-Timeago"

But in the NET feature does not work

http://cerebrumgit.github.io/

https://github.com/cerebrumgit/cerebrumgit.github.io

![captura de tela de 2015-12-30 11 27 57](https://cloud.githubusercontent.com/assets/3661079/12051304/cd773c32-aee8-11e5-8f46-274a4d076ddd.png)
![captura de tela de 2015-12-30 11 29 09](https://cloud.githubusercontent.com/assets/3661079/12051305/cd953fac-aee8-11e5-8722-911138d5a40c.png)

**Comment by markets** [comment]
Hi @cerebrumgit,

GitHub Pages infrastructure doesn't run custom Jekyll plugins for security reasons. You can still use GitHub Pages to publish your site, but you’ll need to convert the site locally and push the generated static files to your GitHub repository.

You can find examples of this workflow here (can be automated easily):

* http://www.sitepoint.com/jekyll-plugins-github/
* http://blog.sorryapp.com/blogging-with-jekyll/2014/01/31/using-jekyll-plugins-on-github-pages.html
* http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html
* https://drewsilcock.co.uk/custom-jekyll-plugins/

Thanks! Stars and sharing are much appreciated!
