### ISSUE TITLE
Doesnt Work on gituhubages

### ISSUE THREAD

**Issue by gagrock** [markets/jekyll-timeago#16]
It works fine on my local system but once I push to remote. It doesn't work

**Comment by markets** [comment]
Hi @gagrock,

GH Pages doesn't allow to run arbitrary Jekyll plugins on their infrastructure, for security reasons: https://github.com/markets/jekyll-timeago/issues/10#issuecomment-168004147.

Thanks! Stars and sharing are much appreciated!
