### ISSUE TITLE
Locales not taken into account

### ISSUE THREAD

**Issue by adham-hajji** [markets/jekyll-timeago#21]
Good afternoon.

I have problems to switch locales from English to French. I tried everything but couldn't manage to switch them. I added the `locale: fr` property into the front matter, I added the `default_local: fr` property in my _config.yml, and finally I downloaded the fr.yml file from the repository.  I wonder if it is a problem of installation. 

Thanks for your help! :)

**Comment by markets** [comment]
Hi @adham-hajji and thanks for trying this plugin! 

First of all, what version are you using? New localization system was released in `v0.10.0`, so you should install an equal or superior version (btw, I recommend you to use latest version `v0.11.1`). 

I'll need more information about your installation and usage to debug your errors. This part has tests and are all passing for me locally and remote CI (Travis).

Keep in touch!

**Comment by markets** [comment]
@adham-hajji maybe you will find useful @david-barbion's comments. 

I'm going to close for now, please reopen if you can provide more information, otherwise we can't help with your issue. Thanks!
