### ISSUE TITLE
Set granularity

### ISSUE THREAD

**Issue by captn3m0** [markets/jekyll-timeago#23]
Setting `depth` decides the number of fields that will show up. A different way might be to set granularity, which decides the most specific time period that will be picked. For eg:

```
granularity: `month`
2 years and 3 months ago
```

```
granularity: `year`
2 years ago
```

```
granularity: `week`
2 years, 3 months, and 1 week ago
```

I'm using the plugin at `https://endoflife.date`, and several scenarios result in the middle time-interval getting skipped. So I see: `2 years and 3 weeks ago` or `1 year and 4 days ago`. (`depth`=2).

It would be much better to have a granularity (say `month`), and any results are at most that granular, unless you are forced to do otherwise (`26 days ago` or `1 week, 3 days to go`).

**Comment by markets** [comment]
Hi :wave: @captn3m0 and thanks for trying this gem! Not sure if I understand your request, you mean something like "accumulate on" or "only" given a time range?

Example: `only: days` will print `7 days` instead of `1 week`

**Comment by captn3m0** [comment]
Basically, `depth` doesn't give me enough customization. It could possibly be solved with `accumulate`, but I'm not sure.

See https://endoflife.date/debian for eg.

I'd want `6 years and 3 weeks ago` to show up as `6 years ago`, and [`Ended 5 months and 2 weeks ago`](https://endoflife.date/php) to show up as `Ended 5 months ago`.

Setting `accumulate_on: :months` as per my understanding would change it to `72 months ago`, which is not what I want.

But if the event is close enough, I'd want to use weeks and days. `2 days ago` should remain so; so should `in 3 weeks`.

As an alternative: I want to avoid stragglers. So anything with a large magnitude difference between the first and second term (`depth: 2` so only 2 terms show up) should automatically remove the second term. Having a `accuracy: 5` parameter that drops all fields < 5% of the previous field for eg.

So `4 weeks and 3 days` is okay (10%), but `6 years and 1 month` is not (1%)

**Comment by markets** [comment]
> Setting accumulate_on: :months as per my understanding would change it to 72 months ago, which is not what I want.

Yep, this is not the feature you want.

I think now I understand. You would like to remove automatically the latest term in case that term is, for example, couple of order of magnitude lower. Sounds useful, but maybe too specific use case? To be honest I've never seen this feature on any "timeago" like plugin. But anyway, we can try to implement it! Pull requests really welcome!

**Comment by captn3m0** [comment]
Filed #24
