### ISSUE TITLE
Can't reverse the order of dates

### ISSUE THREAD

**Issue by matiasilva** [markets/jekyll-timeago#28]
With the following liquid filter, `{{ site.time | timeago: include.event_date }}` I inevitably get "in 1 year and x months" when the event_date is in the past. Is there any way to reverse the calculation?

**Comment by markets** [comment]
Hi @matiasilva one thing you can try is to use the `Liquid Tag` https://github.com/markets/jekyll-timeago#usage-1, which allows you to send 2 parameters, so you can pass the dates in different orders.

**Comment by matiasilva** [comment]
I did try that, but both my dates are variables. I also tried using {{}} in the tags with my variables in them. Sadly, nothing. However, just piping event_data into timeago Just Works, I presume it must check the current time somewhere?

**Comment by markets** [comment]
Probably you will need some custom logic (if/else) in your Liquid template to handle that case dynamically. The gem computes the past/future in the following way:

```ruby
>> timeago(Date.today.prev_day)
=> "yesterday"
>> timeago(Date.today.next_day)
=> "tomorrow"
``` 

Not sure what you mean by "can't reverse the order", maybe you want to force the date to always be as past?

**Comment by matiasilva** [comment]
Exactly! But it's OK, I managed to find a way of going about it. Thanks for the speedy response!
