### ISSUE TITLE
.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/jekyll-timeago-0.15.0/lib/jekyll-timeago/core.rb:36:in `parse': invalid date (Date::Error)

### ISSUE THREAD

**Issue by dcalixto** [markets/jekyll-timeago#38]
this is due ruby 3?

`.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/jekyll-timeago-0.15.0/lib/jekyll-timeago/core.rb:36:in `parse': invalid date (Date::Error)
`

**Comment by markets** [comment]
Hello @dcalixto that seems weird, we already run our CI against Ruby 3 with no problems:

https://github.com/markets/jekyll-timeago/blob/f12f83392d657e46aee3df49fa0b2a03e91c5927/.github/workflows/ci.yml#L14

We'll need more info to understand your problem. How are you using this plugin? Is the repo open-source?

**Comment by markets** [comment]
Please, re-open this issue if you can provide us more info. We can't do so much without understanding your usage.
